ru = {
    "AdventureGuild_KillList_Slimes": "Слаймы",
    "AdventureGuild_KillList_VoidSpirits": "Духи пустоты",
    "AdventureGuild_KillList_Bats": "Летучие мыши",
    "AdventureGuild_KillList_Skeletons": "Скелеты",
    "AdventureGuild_KillList_CaveInsects": "Пещерные насекомые",
    "AdventureGuild_KillList_Duggies": "Копашки",
    "AdventureGuild_KillList_DustSprites": "Пыльные духи",
    "AdventureGuild_KillList_RockCrabs": "Каменные крабы",
    "AdventureGuild_KillList_Mummies": "Мумии",
    "AdventureGuild_KillList_PepperRex": "Перечные динозавры",
    "AdventureGuild_KillList_Serpents": "Змеи",
    "AdventureGuild_KillList_FlameSpirits": "Магмовые духи",

    "Abigail": "Абигейл",
    "Alex": "Алекс",
    "Bear": "Медведь",
    "Birdie": "Пташка",
    "Bouncer": "Вышибала",
    "Caroline": "Кэролайн",
    "Clint": "Клинт",
    "Demetrius": "Деметриус",
    "Dwarf": "Дварф",
    "Elliott": "Эллиот",
    "Emily": "Эмили",
    "Evelyn": "Эвелин",
    "George": "Джордж",
    "Gil": "Гил",
    "Governor": "Губернатор",
    "Grandpa": "Дедушка",
    "Gunther": "Гюнтер",
    "Gus": "Гас",
    "Haley": "Хэйли",
    "Harvey": "Харви",
    "Henchman": "Приспешник",
    "Jas": "Джас",
    "Jodi": "Джоди",
    "Kent": "Кент",
    "Krobus": "Кробус",
    "Leah": "Лея",
    "Leo": "Лео",
    "Lewis": "Льюис",
    "Linus": "Линус",
    "Marlon": "Марлон",
    "Marnie": "Марни",
    "Maru": "Мару",
    "MisterQi": "Мистер Ки",
    "Morris": "Моррис",
    "OldMariner": "Старый мореход",
    "Pam": "Пэм",
    "Penny": "Пенни",
    "Pierre": "Пьер",
    "ProfessorSnail": "Проф. Улиткин",
    "Robin": "Робин",
    "Sam": "Сэм",
    "Sandy": "Сэнди",
    "Sebastian": "Себастиан",
    "Shane": "Шейн",
    "Vincent": "Винсент",
    "Welwick": "Велвик",
    "Willy": "Вилли",
    "Wizard": "Волшебник"
}