ru = {
    "AdventureGuild_KillList_Slimes": "Слаймы",
    "AdventureGuild_KillList_VoidSpirits": "Духи пустоты",
    "AdventureGuild_KillList_Bats": "Летучие мыши",
    "AdventureGuild_KillList_Skeletons": "Скелеты",
    "AdventureGuild_KillList_CaveInsects": "Пещерные насекомые",
    "AdventureGuild_KillList_Duggies": "Копашки",
    "AdventureGuild_KillList_DustSprites": "Пыльные духи",
    "AdventureGuild_KillList_RockCrabs": "Каменные крабы",
    "AdventureGuild_KillList_Mummies": "Мумии",
    "AdventureGuild_KillList_PepperRex": "Перечные динозавры",
    "AdventureGuild_KillList_Serpents": "Змеи",
    "AdventureGuild_KillList_FlameSpirits": "Магмовые духи",

    "Abigail": "Абигейл",
    "Alex": "Алекс",
    "Bear": "Медведь",
    "Birdie": "Пташка",
    "Bouncer": "Вышибала",
    "Caroline": "Кэролайн",
    "Clint": "Клинт",
    "Demetrius": "Деметриус",
    "Dwarf": "Дварф",
    "Elliott": "Эллиот",
    "Emily": "Эмили",
    "Evelyn": "Эвелин",
    "George": "Джордж",
    "Gil": "Гил",
    "Governor": "Губернатор",
    "Grandpa": "Дедушка",
    "Gunther": "Гюнтер",
    "Gus": "Гас",
    "Haley": "Хэйли",
    "Harvey": "Харви",
    "Henchman": "Приспешник",
    "Jas": "Джас",
    "Jodi": "Джоди",
    "Kent": "Кент",
    "Krobus": "Кробус",
    "Leah": "Лея",
    "Leo": "Лео",
    "Lewis": "Льюис",
    "Linus": "Линус",
    "Marlon": "Марлон",
    "Marnie": "Марни",
    "Maru": "Мару",
    "MisterQi": "Мистер Ки",
    "Morris": "Моррис",
    "OldMariner": "Старый мореход",
    "Pam": "Пэм",
    "Penny": "Пенни",
    "Pierre": "Пьер",
    "ProfessorSnail": "Проф. Улиткин",
    "Robin": "Робин",
    "Sam": "Сэм",
    "Sandy": "Сэнди",
    "Sebastian": "Себастиан",
    "Shane": "Шейн",
    "Vincent": "Винсент",
    "Welwick": "Велвик",
    "Willy": "Вилли",
    "Wizard": "Волшебник",

    "Acorn_Name": "Желудь",
    "AdvancedTVRemote_Name": "Прокачанный пульт ДУ",
    "Aerinite_Name": "Эринит",
    "AgedRoe_Name": "Вяленая икра",
    "Alamite_Name": "Алямит",
    "Albacore_Name": "Альбакор",
    "AlgaeSoup_Name": "Суп из водорослей",
    "Amaranth_Name": "Амарант",
    "AmaranthSeeds_Name": "Семена амаранта",
    "Amethyst_Name": "Аметист",
    "AmethystRing_Name": "Кольцо с аметистом",
    "AmethystStone_Name": "Аметистовый камень",
    "AmphibianFossil_Name": "Окаменелая амфибия",
    "Anchor_Name": "Якорь",
    "Anchovy_Name": "Анчоус",
    "AncientDoll_Name": "Древняя кукла",
    "AncientDrum_Name": "Древний барабан",
    "AncientFruit_Name": "Древний плод",
    "AncientSeed_Name": "Древнее семя",
    "AncientSeeds_Name": "Древние семена",
    "AncientSword_Name": "Древний меч",
    "Angler_Name": "Морской черт",
    "Apple_Name": "Яблоко",
    "AppleSapling_Name": "Саженец яблони",
    "Apricot_Name": "Абрикос",
    "ApricotSapling_Name": "Саженец абрикоса",
    "Aquamarine_Name": "Аквамарин",
    "AquamarineRing_Name": "Кольцо с аквамарином",
    "AquamarineStone_Name": "Аквамариновый камень",
    "ArcticShard_Name": "Арктический осколок",
    "Arrowhead_Name": "Наконечник стрелы",
    "Artichoke_Name": "Артишок",
    "ArtichokeDip_Name": "Артишоковый дип",
    "ArtichokeSeeds_Name": "Семена артишока",
    "ArtifactSpot_Name": "Место для артефакта",
    "ArtifactTrove_Name": "Древний клад",
    "AutumnsBounty_Name": "«Дары осени»",
    "Bait_Name": "Наживка",
    "BakedFish_Name": "Запечeнная рыба",
    "Banana_Name": "Банан",
    "BananaPudding_Name": "Банановый пудинг",
    "BananaSapling_Name": "Саженец банана",
    "BarbedHook_Name": "Крючок с бородкой",
    "Baryte_Name": "Барит",
    "Basalt_Name": "Базальт",
    "BasicFertilizer_Name": "Обычное удобрение",
    "BasicRetainingSoil_Name": "Обычная влагосохраняющая почва",
    "BatteryPack_Name": "Аккумулятор",
    "BatWing_Name": "Крыло летучей мыши",
    "BeanHotpot_Name": "Жаркое из фасоли",
    "BeanStarter_Name": "Рассада зеленой фасоли",
    "Beer_Name": "Пиво",
    "Beet_Name": "Свtкла",
    "BeetSeeds_Name": "Семена свеклы",
    "BerryBasket_Name": "Корзина для ягод",
    "Bixite_Name": "Биксит",
    "Blackberry_Name": "Ежевика",
    "BlackberryCobbler_Name": "Ежевичный коблер",
    "Blobfish_Name": "Рыба-пузырь",
    "Blueberry_Name": "Черника",
    "BlueberrySeeds_Name": "Семена черники",
    "BlueberryTart_Name": "Черничный тарт",
    "BlueDiscus_Name": "Голубой дискус",
    "BlueJazz_Name": "Синий яркоцвет",
    "BlueSlimeEgg_Name": "Синее яйцо слайма",
    "BokChoy_Name": "Бок-чой",
    "BokChoySeeds_Name": "Семена бок-чой",
    "Bomb_Name": "Бомба",
    "BoneFlute_Name": "Костяная флейта",
    "BoneFragment_Name": "Кусочек кости",
    "Bouquet_Name": "Букет",
    "Bread_Name": "Хлеб",
    "Bream_Name": "Лещ",
    "BrickFloor_Name": "Кирпичный покрытие",
    "BrokenCD_Name": "Сломанный диск",
    "BrokenGlasses_Name": "Разбитые очки",
    "BrownEgg_Name": "Яйцо",
    "Bruschetta_Name": "Брускетта",
    "BugMeat_Name": "Жучиная плоть",
    "BugSteak_Name": "Жучиный стейк",
    "Bullhead_Name": "Сомик",
    "BurglarsRing_Name": "Воровское кольцо",
    "CactusFruit_Name": "Плод кактуса",
    "CactusSeeds_Name": "Семена кактуса",
    "Calcite_Name": "Кальцит",
    "CampingStove_Name": "Походная печка",
    "Carp_Name": "Карп",
    "CarpSurprise_Name": "Карповый сюрприз",
    "Catfish_Name": "Сом",
    "Cauliflower_Name": "Цветная капуста",
    "CauliflowerSeeds_Name": "Семена цветной капусты",
    "CaveCarrot_Name": "Пещерная морковка",
    "Caviar_Name": "Черная икра",
    "Celestine_Name": "Целестин",
    "Chanterelle_Name": "Лисичка",
    "Cheese_Name": "Сыр",
    "CheeseCauliflower_Name": "Цветная капуста с сыром.",
    "Cherry_Name": "Вишня",
    "CherryBomb_Name": "Бомбочка",
    "CherrySapling_Name": "Саженец вишни",
    "ChewingStick_Name": "Зубная палочка",
    "ChickenStatue_Name": "Статуя курицы",
    "ChippedAmphora_Name": "Битая амфора",
    "ChocolateCake_Name": "Шоколадный торт",
    "Chowder_Name": "Рыбная похлебка",
    "Chub_Name": "Голавль",
    "CinderShard_Name": "Тлеющий осколок",
    "CinderShardStone_Name": "Камень с тлеющими осколками",
    "Clam_Name": "Гребешок",
    "Clay_Name": "Глина",
    "ClayStone_Name": "Глиняный камень",
    "Cloth_Name": "Ткань",
    "Coal_Name": "Уголь",
    "CobblestonePath_Name": "Каменная дорожка",
    "Cockle_Name": "Сердцевидка",
    "Coconut_Name": "Кокос",
    "Coffee_Name": "Кофе",
    "CoffeeBean_Name": "Кофейное зерно",
    "Coleslaw_Name": "Капустный салат",
    "CombinedRing_Name": "Сборное кольцо",
    "CommonMushroom_Name": "Шампиньон",
    "CompleteBreakfast_Name": "Полный завтрак",
    "ConcernedApeMask_Name": "???",
    "Cookie_Name": "Печенье",
    "CookoutKit_Name": "Походная кухня",
    "CopperBar_Name": "Медный слиток",
    "CopperOre_Name": "Медная руда",
    "CopperStone_Name": "Медный камень",
    "Coral_Name": "Коралл",
    "CorkBobber_Name": "Пробковый поплавок",
    "Corn_Name": "Кукуруза",
    "CornSeeds_Name": "Семена кукурузы",
    "Crab_Name": "Краб",
    "CrabCakes_Name": "Крабовые котлетки",
    "CrabPot_Name": "Крабовая ловушка",
    "CrabshellRing_Name": "Крабовое кольцо",
    "Cranberries_Name": "Клюква",
    "CranberryCandy_Name": "Клюквенная сласть",
    "CranberrySauce_Name": "Клюквенный соус",
    "CranberrySeeds_Name": "Семена клюквы",
    "Crayfish_Name": "Рак",
    "Crimsonfish_Name": "Кримзонфиш",
    "CrispyBass_Name": "Окунь с хруст. корочкой",
    "Crocus_Name": "Крокус",
    "CrystalFloor_Name": "Кристальное покрытие",
    "CrystalFruit_Name": "Кристальный фрукт",
    "CrystalPath_Name": "Дорожка из кристаллов",
    "CuriosityLure_Name": "Диковинная приманка",
    "Daffodil_Name": "Нарцисс",
    "Dandelion_Name": "Одуванчик",
    "DecorativePot_Name": "Декоративный горшок",
    "DeluxeFertilizer_Name": "Удобрение Делюкс",
    "DeluxeRetainingSoil_Name": "Влагосохраняющая почва Делюкс",
    "DeluxeSpeedGro_Name": "СкороРост Делюкс",
    "Diamond_Name": "Алмаз",
    "DiamondStone_Name": "Алмазный камень",
    "DinosaurEgg_Name": "Яйцо динозавра",
    "DinosaurMayonnaise_Name": "Динозавровый майонез",
    "DishOTheSea_Name": "«Морское блюдо»",
    "Dolomite_Name": "Доломит",
    "Dorado_Name": "Дорада",
    "DragonTooth_Name": "Драконий зуб",
    "DressedSpinner_Name": "Украшенный спиннер",
    "DriedStarfish_Name": "Высохшая морская звезда",
    "Driftwood_Name": "Плавник",
    "DrumBlock_Name": "Барабан-блок",
    "DuckEgg_Name": "Утиное яйцо",
    "DuckFeather_Name": "Утиное перо",
    "DuckMayonnaise_Name": "Утиный майонез",
    "DwarfGadget_Name": "Устройство дварфов",
    "DwarfScrollI_Name": "Свиток дварфов I",
    "DwarfScrollII_Name": "Свиток дварфов II",
    "DwarfScrollIII_Name": "Свиток дварфов III",
    "DwarfScrollIV_Name": "Свиток дварфов IV",
    "DwarvishHelm_Name": "Шлем дварфов",
    "DwarvishTranslationGuide_Name": "Самоучитель языка дварфов",
    "EarthCrystal_Name": "Земляной кристалл",
    "Ectoplasm_Name": "Эктоплазма",
    "Eel_Name": "Угорь",
    "Eggplant_Name": "Баклажан",
    "EggplantParmesan_Name": "Баклажаны с пармезаном",
    "EggplantSeeds_Name": "Семена баклажана",
    "ElvishJewelry_Name": "Бижутерия эльфов",
    "Emerald_Name": "Изумруд",
    "EmeraldRing_Name": "Кольцо с изумрудом",
    "EmeraldStone_Name": "Изумрудный камень",
    "EnergyTonic_Name": "Энергетический тоник",
    "Enricher_Name": "Обогатитель",
    "Escargot_Name": "Эскарго",
    "Esperite_Name": "Эсперит",
    "ExplosiveAmmo_Name": "Взрывные снаряды",
    "FairyDust_Name": "Волшебный порошок",
    "FairyRose_Name": "Сказочная роза",
    "FairySeeds_Name": "Сказочные семена",
    "FairyStone_Name": "Камень феи",
    "FallSeeds_Name": "Осенние семена",
    "FarmersLunch_Name": "«Обед фермера»",
    "Fiber_Name": "Волокна",
    "FiberSeeds_Name": "Семена волокон",
    "FiddleheadFern_Name": "Съедобный папоротник",
    "FiddleheadRisotto_Name": "Ризотто с папоротником",
    "FieldSnack_Name": "Полевая закуска",
    "FireOpal_Name": "Огненный опал",
    "FireQuartz_Name": "Огненный кварц",
    "FireworksGreen_Name": "Фейерверк (Зеленый)",
    "FireworksPurple_Name": "Фейерверк (Пурпурный)",
    "FireworksRed_Name": "Фейерверк (Красный)",
    "FishStew_Name": "Уха",
    "FishTaco_Name": "Рыбные тако",
    "Flounder_Name": "Мелкая камбала",
    "Fluorapatite_Name": "Фторопатит",
    "FluteBlock_Name": "Флейта-блок",
    "FossilizedLeg_Name": "Окаменевшая нога",
    "FossilizedRibs_Name": "Окаменевшие ребра",
    "FossilizedSkull_Name": "Окаменевший череп",
    "FossilizedSpine_Name": "Окаменевший позвоночник",
    "FossilizedTail_Name": "Окаменевший хвост",
    "FossilStone_Name": "Камень с раскопок",
    "FriedCalamari_Name": "Жареный кальмар",
    "FriedEel_Name": "Жареный угорь",
    "FriedEgg_Name": "Яичница",
    "FriedMushroom_Name": "Жареные грибы",
    "FrozenGeode_Name": "Морозная жеода",
    "FrozenGeodeStone_Name": "Морозножеодный камень",
    "FrozenTear_Name": "Замерзшая слеза",
    "FruitSalad_Name": "Фруктовый салат",
    "GalaxySoul_Name": "Душа Галактики",
    "Garlic_Name": "Чеснок",
    "GarlicSeeds_Name": "Семена чеснока",
    "Gate_Name": "Калитка",
    "Geminite_Name": "Геминит",
    "GemStone_Name": "Самоцветный камень",
    "Geode_Name": "Жеода",
    "GeodeStone_Name": "Жеодовый камень",
    "GhostCrystal_Name": "Призрачный кристалл",
    "Ghostfish_Name": "Пятнистый криворот",
    "Ginger_Name": "Имбирь",
    "GingerAle_Name": "Имбирный эль",
    "Glacierfish_Name": "Ледорыб",
    "GlacierfishJr_Name": "Ледорыб Мл.",
    "GlassShards_Name": "Битое стекло",
    "GlazedYams_Name": "Глазированный батат",
    "GlowRing_Name": "Кольцо света",
    "GlowstoneRing_Name": "Светокаменное кольцо",
    "GoatCheese_Name": "Козий сыр",
    "GoatMilk_Name": "Бутыль козьего молока",
    "GoldBar_Name": "Золотой слиток",
    "GoldenCoconut_Name": "Золотой кокос",
    "GoldenEgg_Name": "Золотое яйцо",
    "GoldenMask_Name": "Золотая маска",
    "GoldenPumpkin_Name": "Золотая тыква",
    "GoldenRelic_Name": "Золотая реликвия",
    "GoldenWalnut_Name": "Золотой грецкий орех",
    "GoldOre_Name": "Золотая руда",
    "GoldStone_Name": "Золотой камень",
    "GourmetTomatoSalt_Name": "Изысканная помидорная соль",
    "Granite_Name": "Гранит",
    "Grape_Name": "Виноград",
    "GrapeStarter_Name": "Виноградные черенки",
    "GrassStarter_Name": "Рассада травы",
    "GravelPath_Name": "Дорожка из гравия",
    "GreenAlgae_Name": "Зелeная водоросль",
    "GreenBean_Name": "Зеленая фасоль",
    "GreenSlimeEgg_Name": "Зеленое яйцо слайма",
    "GreenTea_Name": "Зеленый чай",
    "HaleysLostBracelet_Name": "Потерянный браслет Хэйли",
    "Halibut_Name": "Камбала",
    "Hardwood_Name": "Твердая древесина",
    "HardwoodFence_Name": "Забор из твердой древесины",
    "Hashbrowns_Name": "Хашбраун",
    "Hay_Name": "Сено",
    "Hazelnut_Name": "Фундук",
    "Hedge_Name": "Живая изгородь",
    "Helvite_Name": "Гельвин",
    "Hematite_Name": "Гематит",
    "Herring_Name": "Сельдь",
    "Holly_Name": "Остролист",
    "Honey_Name": "Мед",
    "Hops_Name": "Хмель",
    "HopsStarter_Name": "Рассада хмеля",
    "HorseFlute_Name": "Лошадиная дудочка",
    "HotJavaRing_Name": "Кольцо Горячего кофе",
    "HotPepper_Name": "Жгучий перец",
    "HyperSpeedGro_Name": "Гипер СкороРост",
    "IceCream_Name": "Мороженое",
    "IceCrystal_Name": "Ледяной кристалл",
    "IcePip_Name": "Ледопип",
    "ImmunityBand_Name": "Кольцо Стойкости",
    "IridiumBand_Name": "Иридиевый обод",
    "IridiumBar_Name": "Иридиевый слиток",
    "IridiumMilk_Name": "Иридиевое молоко",
    "IridiumOre_Name": "Иридиевая руда",
    "IridiumSprinkler_Name": "Иридиевый спринклер",
    "IridiumStone_Name": "Иридиевый камень",
    "IronBar_Name": "Железный слиток",
    "IronFence_Name": "Железный забор",
    "IronOre_Name": "Железная руда",
    "IronStone_Name": "Железный камень",
    "JackOLantern_Name": "Фонарь из тыквы",
    "Jade_Name": "Нефрит",
    "JadeRing_Name": "Кольцо с нефритом",
    "JadeStone_Name": "Нефритовый камень",
    "Jagoite_Name": "Ягоит",
    "Jamborite_Name": "Джамборит",
    "Jasper_Name": "Яшма",
    "JazzSeeds_Name": "Семена яркоцвета",
    "Jelly_Name": "Джем",
    "JojaCola_Name": "Джоджа-кола",
    "JournalScrap_Name": "Обрывок дневника",
    "Juice_Name": "Сок",
    "JukeboxRing_Name": "Музыкальное кольцо",
    "Kale_Name": "Кудрявая капуста",
    "KaleSeeds_Name": "Семена кудрявой капусты",
    "Kyanite_Name": "Кианит",
    "LargeBrownEgg_Name": "Большое яйцо",
    "LargeMilk_Name": "Бидон молока",
    "LargemouthBass_Name": "Большеротый окунь",
    "LargeWhiteEgg_Name": "Большое яйцо",
    "LavaEel_Name": "Лавовый угорь",
    "LeadBobber_Name": "Свинцовый поплавок",
    "Leek_Name": "Лук-порей",
    "Legend_Name": "Легенда",
    "LegendII_Name": "Легенда II",
    "LemonStone_Name": "Лемонстон",
    "LGoatMilk_Name": "Бол. бутыль козьего молока",
    "LifeElixir_Name": "Эликсир жизни",
    "Limestone_Name": "Известняк",
    "Lingcod_Name": "Змеезуб",
    "Lionfish_Name": "Морской ёрш",
    "Lobster_Name": "Омар",
    "LobsterBisque_Name": "Биск из омара",
    "LostAxe_Name": "Потерянный топор",
    "LostBook_Name": "Потерянная книга",
    "LuckyLunch_Name": "Обед на удачу",
    "LuckyPurpleShorts_Name": "Фиолетовые шорты",
    "LuckyRing_Name": "Кольцо Удачи",
    "Lumber_Name": "Древесина",
    "Lunarite_Name": "Лунарит",
    "MagicBait_Name": "Волшебная приманка",
    "MagicRockCandy_Name": "Волшебный леденец",
    "MagmaCap_Name": "Магмовый гриб",
    "MagmaGeode_Name": "Магма-жеода",
    "MagmaGeodeStone_Name": "Магма-жеодовый камень",
    "Magnet_Name": "Магнит",
    "MagnetRing_Name": "Кольцо-магнит",
    "MahoganySeed_Name": "Семя красного дерева",
    "MakiRoll_Name": "Суши-роллы",
    "Malachite_Name": "Малахит",
    "Mango_Name": "Манго",
    "MangoSapling_Name": "Саженец манго",
    "MangoStickyRice_Name": "Манговый клейкий рис",
    "MapleBar_Name": "Кленовый пончик",
    "MapleSeed_Name": "Кленовое семя",
    "MapleSyrup_Name": "Кленовый сироп",
    "Marble_Name": "Мрамор",
    "Mayonnaise_Name": "Майонез",
    "Mead_Name": "Медовуха",
    "MegaBomb_Name": "Мегабомба",
    "Melon_Name": "Дыня",
    "MelonSeeds_Name": "Семена дыни",
    "MermaidsPendant_Name": "Кулон Русалки",
    "MidnightCarp_Name": "Полуночный карп",
    "MidnightSquid_Name": "Ночной кальмар",
    "Milk_Name": "Ведерко молока",
    "MinersTreat_Name": "«Шахтерский леденец»",
    "MixedSeeds_Name": "Смешанные семена",
    "MonsterMusk_Name": "Монстрячий мускус",
    "Morel_Name": "Сморчок",
    "MovieTicket_Name": "Билет в кино",
    "MsAngler_Name": "Мисс Морской черт",
    "Mudstone_Name": "Аргиллит",
    "MummifiedBat_Name": "Мумифицированная летучая мышь",
    "MummifiedFrog_Name": "Мумифицированная лягушка",
    "MuscleRemedy_Name": "Лекарство для мышц",
    "MushroomTreeSeed_Name": "Семя грибного дерева",
    "Mussel_Name": "Мидия",
    "MusselStone_Name": "Ракушковый камень",
    "MutantCarp_Name": "Карп-мутант",
    "MysticStone_Name": "Загадочный камень",
    "NapalmRing_Name": "Напалмовое кольцо",
    "NautilusFossil_Name": "Окаменелый наутилус",
    "NautilusShell_Name": "Раковина наутилуса",
    "Nekoite_Name": "Некоит",
    "Neptunite_Name": "Нептунит",
    "OakResin_Name": "Дубовая смола",
    "Obsidian_Name": "Обсидиан",
    "OceanStone_Name": "Океаниум",
    "Octopus_Name": "Осьминог",
    "Oil_Name": "Масло",
    "OilofGarlic_Name": "Масло Чеснока",
    "Omelet_Name": "Омлет",
    "OmniGeode_Name": "Омнижеода",
    "OmniGeodeStone_Name": "Омнижеодовый камень",
    "Opal_Name": "Опал",
    "Orange_Name": "Апельсин",
    "OrangeSapling_Name": "Саженец апельсина",
    "OrnamentalFan_Name": "Декоративный веер",
    "OrnateNecklace_Name": "Резное ожерелье",
    "Orpiment_Name": "Орпимент",
    "OstrichEgg_Name": "Страусиное яйцо",
    "Oyster_Name": "Устрица",
    "PaleAle_Name": "Светлый эль",
    "PaleBroth_Name": "Светлый бульон",
    "PalmFossil_Name": "Окаменелая пальма",
    "Pancakes_Name": "Блины",
    "Parsnip_Name": "Пастернак",
    "ParsnipSeeds_Name": "Семена пастернака",
    "ParsnipSoup_Name": "Суп из пастернака",
    "Peach_Name": "Персик",
    "PeachSapling_Name": "Саженец персика",
    "Pearl_Name": "Жемчужина",
    "PepperPoppers_Name": "Перечные бомбочки",
    "PepperSeeds_Name": "Семена перца",
    "Perch_Name": "Окунь",
    "Periwinkle_Name": "Литорина",
    "PetrifiedSlime_Name": "Окаменелый слайм",
    "PhoenixRing_Name": "Кольцо Феникса",
    "Pickles_Name": "Консервы",
    "PierresMissingStocklist_Name": "Потерянная инвентарная опись Пьера",
    "Pike_Name": "Щука",
    "PinaColada_Name": "Пина колада",
    "Pineapple_Name": "Ананас",
    "PineappleSeeds_Name": "Семена ананаса",
    "PineCone_Name": "Сосновая шишка",
    "PineTar_Name": "Сосновая смола",
    "PinkCake_Name": "Розовый торт",
    "PiratesLocket_Name": "Пиратский медальон",
    "Pizza_Name": "Пицца",
    "PlumPudding_Name": "Сливовый пудинг",
    "Poi_Name": "Пои",
    "Pomegranate_Name": "Гранат",
    "PomegranateSapling_Name": "Саженец граната",
    "Poppy_Name": "Мак",
    "PoppyseedMuffin_Name": "Маффин с маком",
    "PoppySeeds_Name": "Семена мака",
    "Potato_Name": "Картофель",
    "PotatoSeeds_Name": "Семена картофеля",
    "PrehistoricHandaxe_Name": "Доисторический топор",
    "PrehistoricRib_Name": "Доисторическое ребро",
    "PrehistoricScapula_Name": "Доисторическая скапула",
    "PrehistoricSkull_Name": "Доисторический череп",
    "PrehistoricTibia_Name": "Доисторическая берцовая кость",
    "PrehistoricTool_Name": "Доисторический инструмент",
    "PrehistoricVertebra_Name": "Доисторический позвонок",
    "PressureNozzle_Name": "Нагнетательное сопло",
    "PrismaticJelly_Name": "Радужное желе",
    "PrismaticShard_Name": "Радужный осколок",
    "ProtectionRing_Name": "Защитное кольцо",
    "Pufferfish_Name": "Рыба-еж",
    "Pumpkin_Name": "Тыква",
    "PumpkinPie_Name": "Тыквенный пирог",
    "PumpkinSeeds_Name": "Семена тыквы",
    "PumpkinSoup_Name": "Тыквенный суп",
    "PurpleMushroom_Name": "Фиолетовый гриб",
    "PurpleSlimeEgg_Name": "Фиолетовое яйцо слайма",
    "Pyrite_Name": "Пирит",
    "QiBean_Name": "Семя Ки",
    "QiFruit_Name": "Фрукт Ки",
    "QiGem_Name": "Драгоценный камень Ки",
    "QiSeasoning_Name": "Приправа Ки",
    "QualityBobber_Name": "Высококачественный поплавок",
    "QualityFertilizer_Name": "Высококачественное удобрение",
    "QualityRetainingSoil_Name": "Высококачественная влагосохраняющая почва",
    "QualitySprinkler_Name": "Высококачественный спринклер",
    "Quartz_Name": "Кварц",
    "RabbitsFoot_Name": "Кроличья лапка",
    "RadioactiveBar_Name": "Радиоактивный слиток",
    "RadioactiveCarp_Name": "Радиоактивный карп",
    "RadioactiveOre_Name": "Радиоактивная руда",
    "RadioactiveStone_Name": "Радиоактивный камень",
    "Radish_Name": "Редис",
    "RadishSalad_Name": "Салат из редиса",
    "RadishSeeds_Name": "Семена редиса",
    "RainbowShell_Name": "Радужная ракушка",
    "RainbowTrout_Name": "Радужная форель",
    "RainTotem_Name": "Тотем дождя",
    "RareDisc_Name": "Редкий диск",
    "RareSeed_Name": "Редкое семечко",
    "RedCabbage_Name": "Красная капуста",
    "RedCabbageSeeds_Name": "Семена красной капусты",
    "RedMullet_Name": "Барабулька",
    "RedMushroom_Name": "Красный гриб",
    "RedPlate_Name": "Красное блюдо",
    "RedSlimeEgg_Name": "Красное яйцо слайма",
    "RedSnapper_Name": "Берикс",
    "RefinedQuartz_Name": "Очищенный кварц",
    "Rhubarb_Name": "Ревень",
    "RhubarbPie_Name": "Пирог с ревенем",
    "RhubarbSeeds_Name": "Семена ревеня",
    "Rice_Name": "Рис",
    "RicePudding_Name": "Рисовый пудинг",
    "RiceShoot_Name": "Росток риса",
    "RingofYoba_Name": "Кольцо Иобы",
    "RoastedHazelnuts_Name": "Жареный фундук",
    "Roe_Name": "Икра",
    "RootsPlatter_Name": "Коренья на блюде",
    "RottenPlant_Name": "Гнилое растение",
    "Ruby_Name": "Рубин",
    "RubyRing_Name": "Кольцо с рубином",
    "RubyStone_Name": "Рубиновый камень",
    "RusticPlankFloor_Name": "Грубоватое дощатое покрытие",
    "RustyCog_Name": "Ржавая шестерня",
    "RustySpoon_Name": "Ржавая ложка",
    "RustySpur_Name": "Ржавая шпора",
    "Salad_Name": "Салат",
    "Salmon_Name": "Лосось",
    "Salmonberry_Name": "Морошка",
    "SalmonDinner_Name": "Ужин из лосося",
    "Sandfish_Name": "Песковник",
    "Sandstone_Name": "Песчаник",
    "Sap_Name": "Древесный сок",
    "Sardine_Name": "Сардина",
    "Sashimi_Name": "Сашими",
    "SavageRing_Name": "Кольцо дикаря",
    "ScorpionCarp_Name": "Скорпионовый карп",
    "SeaCucumber_Name": "Морской огурец",
    "SeafoamPudding_Name": "Морской пенный пудинг",
    "SeaUrchin_Name": "Морской еж",
    "Seaweed_Name": "Морская водоросль",
    "SecretNote_Name": "Секретная заметка",
    "Shad_Name": "Шэд",
    "Shrimp_Name": "Креветка",
    "ShrimpCocktail_Name": "Креветочный коктейль",
    "SkeletalHand_Name": "Рука скелета",
    "SkeletalTail_Name": "Хвост скелета",
    "Slate_Name": "Сланец",
    "Slime_Name": "Слизь",
    "SlimeCharmerRing_Name": "Кольцо укротителя слаймов",
    "SlimeCrate_Name": "Ящик слайма",
    "Slimejack_Name": "Слаймджек",
    "SmallGlowRing_Name": "Малое кольцо света",
    "SmallMagnetRing_Name": "Малое кольцо-магнит",
    "SmallmouthBass_Name": "Малоротый окунь",
    "Snail_Name": "Улитка",
    "SnakeSkull_Name": "Змеиный череп",
    "SnakeVertebrae_Name": "Змеиный позвоночник",
    "SnowYam_Name": "Снежный батат",
    "SnowyStone_Name": "Заснеженный камень",
    "Soapstone_Name": "Талькохлорит",
    "SoggyNewspaper_Name": "Мокрая газета",
    "SolarEssence_Name": "Солнечная эссенция",
    "SonofCrimsonfish_Name": "Сын Кримзонфиш",
    "SoulSapperRing_Name": "Подрывное кольцо души",
    "Spaghetti_Name": "Спагетти",
    "SpangleSeeds_Name": "Семена блестника",
    "SpeedGro_Name": "СкороРост",
    "SpiceBerry_Name": "Острая ягода",
    "SpicyEel_Name": "Острый угорь",
    "Spinner_Name": "Спиннер",
    "SpiritTorch_Name": "Факел духов",
    "SpookFish_Name": "Жуть-рыба",
    "SpringOnion_Name": "Лук-батун",
    "SpringSeeds_Name": "Весенние семена",
    "Sprinkler_Name": "Спринклер",
    "Squid_Name": "Кальмар",
    "SquidInk_Name": "Чернила кальмара",
    "SquidInkRavioli_Name": "Равиоли с чернилами кальмара",
    "StardewValleyRose_Name": "Роза Долины Стардью",
    "Stardrop_Name": "Звездная капля",
    "Starfruit_Name": "Карамбола",
    "StarfruitSeeds_Name": "Семена карамболы",
    "StarShards_Name": "Звездные осколки",
    "SteppingStonePath_Name": "Дорожка из крупных камней",
    "Stingray_Name": "Скат",
    "StirFry_Name": "Стир-фрай",
    "Stone_Name": "Камень",
    "Stone_Node_Name": "Камень",
    "Stone_NodeStoneOnly_Name": "Камень",
    "Stone_NodeWithCoal_Name": "Камень",
    "StoneBase_Name": "Каменный постамент",
    "StoneFence_Name": "Каменный забор",
    "Stonefish_Name": "Камень-рыба",
    "StoneFloor_Name": "Каменное покрытие",
    "StoneWalkwayFloor_Name": "Каменное тротуарное покрытие",
    "StrangeBun_Name": "Странная булочка",
    "StrangeDoll_Name": "Странная кукла",
    "Strawberry_Name": "Клубника",
    "StrawberrySeeds_Name": "Семена клубники",
    "StrawFloor_Name": "Соломенное покрытие",
    "Stuffing_Name": "«Объеденье»",
    "SturdyRing_Name": "Кольцо стойкости",
    "Sturgeon_Name": "Осетр",
    "Sugar_Name": "Сахар",
    "SummerSeeds_Name": "Летние семена",
    "SummerSpangle_Name": "Летний блестник",
    "Sunfish_Name": "Санфиш",
    "Sunflower_Name": "Подсолнух",
    "SunflowerSeeds_Name": "Семена подсолнуха",
    "SuperCucumber_Name": "Чудо-огурец",
    "SuperMeal_Name": "Чудо-блюдо",
    "SupplyCrate_Name": "Ящик с припасами",
    "SurvivalBurger_Name": "«Бургер для выживания»",
    "SweetGemBerry_Name": "Сладкая ягодка",
    "SweetPea_Name": "Душистый горошек",
    "TaroRoot_Name": "Корень Таро",
    "TaroTuber_Name": "Клубень Таро",
    "TeaLeaves_Name": "Чайные листья",
    "TeaSapling_Name": "Саженец чая",
    "TeaSet_Name": "Чайный набор",
    "ThornsRing_Name": "Кольцо Шипов",
    "ThunderEgg_Name": "Громовое яйцо",
    "Tigerseye_Name": "Тигровый глаз",
    "TigerSlimeEgg_Name": "Яйцо Тигрового слайма",
    "TigerTrout_Name": "Тигровая форель",
    "Tilapia_Name": "Тиляпия",
    "Tomato_Name": "Помидор",
    "TomatoSeeds_Name": "Семена помидора",
    "TomKhaSoup_Name": "Суп том кха",
    "Topaz_Name": "Топаз",
    "TopazRing_Name": "Кольцо с топазом",
    "TopazStone_Name": "Топазный камень",
    "Torch_Name": "Факел",
    "Tortilla_Name": "Тортилья",
    "TrapBobber_Name": "Мини-ловушка",
    "Trash_Name": "Мусор",
    "TreasureChest_Name": "Сундук с сокровищами",
    "TreasureHunter_Name": "«Искатель сокровищ»",
    "TreeFertilizer_Name": "Древесное удобрение",
    "Trilobite_Name": "Трилобит",
    "TrimmedLuckyPurpleShorts_Name": "Счастливые фиолетовые шорты с оторочкой",
    "TripleShotEspresso_Name": "Тройной эспрессо",
    "TropicalCurry_Name": "Тропическое карри",
    "TroutSoup_Name": "Уха из форели",
    "Truffle_Name": "Трюфель",
    "TruffleOil_Name": "Трюфельное масло",
    "Tulip_Name": "Тюльпан",
    "TulipBulb_Name": "Луковица тюльпана",
    "Tuna_Name": "Тунец",
    "Twig_Name": "Палка",
    "UnmilledRice_Name": "Неизмельченный рис",
    "VampireRing_Name": "Кольцо вампира",
    "VegetableMedley_Name": "Овощное ассорти",
    "Vinegar_Name": "Уксус",
    "VoidEgg_Name": "Яйцо пустоты",
    "VoidEssence_Name": "Эссенция пустоты",
    "VoidGhostPendant_Name": "Кулон призрачной пустоты",
    "VoidMayonnaise_Name": "Майонез Пустоты",
    "VoidSalmon_Name": "Лосось пустоты",
    "Walleye_Name": "Желтый судак",
    "WarMemento_Name": "Боевой трофей",
    "WarpTotemBeach_Name": "Тотем-телепорт: Пляж",
    "WarpTotemDesert_Name": "Тотем-телепорт: Пустыня",
    "WarpTotemFarm_Name": "Тотем-телепорт: Ферма",
    "WarpTotemIsland_Name": "Тотем-телепорт: Остров",
    "WarpTotemMountains_Name": "Тотем-телепорт: Горы",
    "WarpTotemQisArena_Name": "Тотем-телепорт: Арена Ки",
    "WarriorRing_Name": "Кольцо воина",
    "WeatheredFloor_Name": "Потертое покрытие",
    "WeddingRing_Name": "Обручальное кольцо",
    "Weeds_Name": "Сорняки",
    "Weeds_DryBush_Name": "Сорняки",
    "Weeds_Fiber_Ugly_Name": "Сорняки",
    "Weeds_FiberOrMixedSeeds_Name": "Сорняки",
    "Weeds_FiberOrMixedSeeds_Ugly_Name": "Сорняки",
    "Wheat_Name": "Пшеница",
    "WheatFlour_Name": "Пшеничная мука",
    "WheatSeeds_Name": "Семена пшеницы",
    "WhiteAlgae_Name": "Белая водоросль",
    "WhiteEgg_Name": "Яйцо",
    "WildBait_Name": "Дикая наживка",
    "WildHorseradish_Name": "Дикий хрен",
    "WildPlum_Name": "Черная слива",
    "WiltedBouquet_Name": "Увядший букет",
    "Wine_Name": "Вино",
    "WinterRoot_Name": "Зимний корень",
    "WinterSeeds_Name": "Зимние семена",
    "Wood_Name": "Древесина",
    "WoodFence_Name": "Деревянный забор",
    "WoodFloor_Name": "Деревянное покрытие",
    "WoodPath_Name": "Деревянная дорожка",
    "Woodskip_Name": "Лесоплюх",
    "Wool_Name": "Шерсть",
    "WrigglingWorm_Name": "Извивающийся червь",
    "Yam_Name": "Батат",
    "YamSeeds_Name": "Семена батата",
    "FarAwayStone_Name": "Камень издалека",
    "CalicoEgg_Name": "Яйцо Калико",
    "MixedFlowerSeeds_Name": "Смешанные цветочные семена",
    "GoldenBobber_Name": "Золотой поплавок",
    "CalicoEggStone_Name": "Камень Яйца Калико",
    "MysteryBox_Name": "Загадочная коробка",
    "TroutDerbyTag_Name": "Золотой ярлык",
    "DeluxeBait_Name": "Элитная наживка",
    "Moss_Name": "Мох",
    "MossySeed_Name": "Семечко мха",
    "GreenRainWeeds_Name": "Сорняки зеленого дождя",
    "SonarBobber_Name": "Сонарный поплавок",
    "SpecificBait_Name": "Наживка",
    "TentKit_Name": "Набор с палаткой",
    "VolcanoGoldNode_Name": "Золотой камень",
    "MysticTreeSeed_Name": "Семечко Таинственного дерева",
    "MysticSyrup_Name": "Таинственный сироп",
    "Raisins_Name": "Изюм",
    "DriedFruit_Name": "(Засуш.)",
    "DriedMushrooms_Name": "(Засуш.)",
    "StardropTea_Name": "Чай из звездной капли",
    "PrizeTicket_Name": "Призовой билет",
    "GoldCoin_Name": "Золотая монета",
    "TreasureTotem_Name": "Тотем для сокровищ",
    "ChallengeBait_Name": "Сложная наживка",
    "CarrotSeeds_Name": "Семена морковки",
    "Carrot_Name": "Морковка",
    "SummerSquashSeeds_Name": "Семена сквоша",
    "SummerSquash_Name": "Сквош",
    "BroccoliSeeds_Name": "Семена брокколи",
    "Broccoli_Name": "Брокколи",
    "PowdermelonSeeds_Name": "Семена снегодыни",
    "Powdermelon_Name": "Снегодыня",
    "SmokedFish_Name": "(Копч.)",
}